import "./components/dynamic-adapt";
import "./components/lang";
import "./components/burger";
import "./components/get-header";
import "./components/scrollTo";
import "./components/leaders-cards";
import "./components/pipe";
import "./components/swiper";
import "./components/menu";
